services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reservapp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
